name: Fetch and Convert Files

on:
  push:
    branches:
      - clash
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyyaml requests
    
    - name: Run fetch and convert script
      run: |
        python fetch_and_convert.py

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git diff-index --quiet HEAD || git commit -m "Auto-fetched and converted files to YAML"
        git push origin clash || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 