name: Fetch and Convert Files

on:
  push:
    branches:
      - clash  # 当推送到 clash 分支时运行工作流
  schedule:
    - cron: '0 0 * * *'  # 每天自动运行一次

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyyaml requests
    
    - name: List files
      run: ls -la
  
    - name: Run fetch and convert script
      run: |
        python convert_and_fetch.py

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Auto-fetched and converted files to YAML"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
