name: Process and Fetch Rule

on:
  push:
    branches:
      - clash
    paths:
      - 'user_rule/**'
      - 'script/*.json'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check-changes.outputs.has_changes }}  # 将 has_changes 作为作业输出
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for changes in user_rule directory
        id: check-changes
        run: |
          # 检查 user_rule 目录是否有更改
          if git diff --quiet HEAD^ HEAD -- user_rule; then
            echo "No changes in user_rule directory."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in user_rule directory."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Process Rule Python script
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          python3 script/process_rule.py

      - name: Commit processed rule changes
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Processed rule files with total rules count and sorted rules" || echo "No changes to commit"
          git push

  fetch_and_convert:
    runs-on: ubuntu-latest
    needs: process
    if: ${{ always() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml requests

      - name: Run fetch and convert script
        run: |
          python script/fetch_and_convert.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "没有文件更改，跳过提交。"
          else
            git commit -m "Auto-fetched and converted files to YAML"
            git pull origin clash --rebase
            if git push origin clash; then
              echo "推送成功。"
            else
              echo "推送失败，请检查远程分支是否有冲突。"
              exit 1
            fi
          fi